import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sys
import os

def analyze_results(csv_path):
    # 1. Load Data
    if not os.path.exists(csv_path):
        print(f"Error: {csv_path} not found. Run batch_process.py first.")
        return

    df = pd.read_csv(csv_path)
    print(f"Loaded {len(df)} entries.")
    
    # Filter for Valid Barrels only
    valid_df = df[df['status'] == 'OK'].copy()
    print(f"Valid Barrels: {len(valid_df)} ({len(valid_df)/len(df)*100:.1f}%)")
    
    if valid_df.empty:
        print("No valid data to plot.")
        return

    # Set style
    sns.set_theme(style="whitegrid")
    
    # --- Plot 1: Strand Count Distribution ---
    plt.figure(figsize=(10, 6))
    sns.countplot(x='n_strands', data=valid_df, palette='viridis')
    plt.title("Distribution of Beta-Barrel Sizes (n)")
    plt.xlabel("Number of Strands (n)")
    plt.ylabel("Count")
    plt.savefig('plot_n_distribution.png')
    print("Saved plot_n_distribution.png")
    
    # --- Plot 2: Shear Number vs Strand Count (Murzin Plot) ---
    # Theoretical lines
    n_range = np.linspace(8, 26, 100)
    # Ideal Shear for Tilt=45 deg: S = n * (4.4/3.3) * 1.0 = 1.33n
    # Ideal Shear for Tilt=35 deg: S = n * (4.4/3.3) * 0.7 = 0.93n
    
    plt.figure(figsize=(10, 8))
    sns.scatterplot(
        data=valid_df, 
        x='n_strands', 
        y='shear_S', 
        hue='tilt', 
        size='radius',
        palette='magma',
        sizes=(20, 200),
        alpha=0.7
    )
    
    # Add theoretical reference lines
    plt.plot(n_range, n_range * 1.33, 'r--', label='Tilt=45° (High Shear)')
    plt.plot(n_range, n_range * 0.93, 'b--', label='Tilt=35° (Low Shear)')
    
    plt.title("The Murzin Plot: Shear (S) vs Strands (n)")
    plt.legend(bbox_to_anchor=(1.05, 1), loc=2, borderaxespad=0.)
    plt.grid(True, linestyle='--', alpha=0.6)
    plt.tight_layout()
    plt.savefig('plot_murzin_shear.png')
    print("Saved plot_murzin_shear.png")
    
    # --- Plot 3: Radius vs Strands ---
    # R = n * a / (2 * pi * cos(alpha))
    # Roughly linear
    plt.figure(figsize=(8, 6))
    sns.regplot(data=valid_df, x='n_strands', y='radius', scatter_kws={'alpha':0.5}, line_kws={'color':'red'})
    plt.title("Barrel Radius scaling with Strands")
    plt.savefig('plot_radius_scaling.png')
    print("Saved plot_radius_scaling.png")
    
    # --- Plot 4: Quality Control (Inlier Ratio vs Confidence) ---
    plt.figure(figsize=(8, 6))
    sns.scatterplot(data=df, x='inlier_ratio', y='confidence', hue='status', alpha=0.6)
    plt.axvline(0.4, color='r', linestyle='--', label='Cutoff')
    plt.axhline(0.6, color='r', linestyle='--', label='Cutoff')
    plt.title("Quality Control Landscape")
    plt.savefig('plot_qc.png')
    print("Saved plot_qc.png")

if __name__ == "__main__":
    # Default to the file generated by batch_process
    csv_file = "barrel_census.csv"
    if len(sys.argv) > 1:
        csv_file = sys.argv[1]
    
    analyze_results(csv_file)